INSERT INTO user(id, username) VALUES (1, 'kowalski 1');
INSERT INTO user(id, username) VALUES (2, 'kowalski 2');
INSERT INTO user(id, username) VALUES (3, 'kowalski 3');
INSERT INTO user(id, username) VALUES (4, 'kowalski 4');
INSERT INTO user(id, username) VALUES (5, 'kowalski 5');
INSERT INTO user(id, username) VALUES (6, 'kowalski 6');
INSERT INTO user(id, username) VALUES (7, 'kowalski 7');
INSERT INTO user(id, username) VALUES (8, 'kowalski 8');
INSERT INTO user(id, username) VALUES (9, 'kowalski 9');
INSERT INTO user(id, username) VALUES (10, 'kowalski 10');

INSERT INTO address(id, user_id, street, zip_code,city) VALUES (1, 1, 'ul. Marszałkowska 1', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (2, 1, 'ul. Marszałkowska 2', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (3, 1, 'ul. Marszałkowska 3', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (4, 1, 'ul. Marszałkowska 4', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (5, 1, 'ul. Marszałkowska 5', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (6, 2, 'ul. Marszałkowska 6', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (7, 2, 'ul. Marszałkowska 7', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (8, 2, 'ul. Marszałkowska 8', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (9, 2, 'ul. Marszałkowska 9', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (10, 2, 'ul. Marszałkowska 10', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (11, 3, 'ul. Marszałkowska 11', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (12, 3, 'ul. Marszałkowska 12', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (13, 3, 'ul. Marszałkowska 13', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (14, 3, 'ul. Marszałkowska 14', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (15, 3, 'ul. Marszałkowska 15', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (16, 4, 'ul. Marszałkowska 16', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (17, 4, 'ul. Marszałkowska 17', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (18, 4, 'ul. Marszałkowska 18', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (19, 4, 'ul. Marszałkowska 19', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (20, 4, 'ul. Marszałkowska 20', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (21, 5, 'ul. Marszałkowska 21', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (22, 5, 'ul. Marszałkowska 22', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (23, 5, 'ul. Marszałkowska 23', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (24, 5, 'ul. Marszałkowska 24', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (25, 5, 'ul. Marszałkowska 25', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (26, 6, 'ul. Marszałkowska 26', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (27, 6, 'ul. Marszałkowska 27', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (28, 6, 'ul. Marszałkowska 28', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (29, 6, 'ul. Marszałkowska 29', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (30, 6, 'ul. Marszałkowska 30', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (31, 7, 'ul. Marszałkowska 31', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (32, 7, 'ul. Marszałkowska 32', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (33, 7, 'ul. Marszałkowska 33', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (34, 7, 'ul. Marszałkowska 34', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (35, 7, 'ul. Marszałkowska 35', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (36, 8, 'ul. Marszałkowska 36', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (37, 8, 'ul. Marszałkowska 37', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (38, 8, 'ul. Marszałkowska 38', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (39, 8, 'ul. Marszałkowska 39', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (40, 8, 'ul. Marszałkowska 40', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (41, 9, 'ul. Marszałkowska 41', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (42, 9, 'ul. Marszałkowska 42', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (43, 9, 'ul. Marszałkowska 43', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (44, 9, 'ul. Marszałkowska 44', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (45, 9, 'ul. Marszałkowska 45', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (46, 10, 'ul. Marszałkowska 46', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (47, 10, 'ul. Marszałkowska 47', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (48, 10, 'ul. Marszałkowska 48', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (49, 10, 'ul. Marszałkowska 49', '00-950', 'Warszawa');
INSERT INTO address(id, user_id, street, zip_code,city) VALUES (50, 10, 'ul. Marszałkowska 50', '00-950', 'Warszawa');
